### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by benstr** [coolaj86/yaml2json#4]
Receive an error when using yaml2json to parse the following. Online parsers work fine. Cannot find any similar issues online. I also tried a yaml file that had the strings quoted but got the same issue.

YAML:

```

---
  foo: bar
  baz:
    - qux
    - quxx
  corge: null
  grault: 1
  garply: true
  waldo: "false"
  fred: undefined
```

CLI

```
$ yaml2json ./example.yml
```

CONSOLE ERROR

```
/Users/user/.nvm/v0.10.29/lib/node_modules/yaml2json/node_modules/yaml/lib/yaml.js:179
  throw new Error(msg + ', ' + context(this.peek()[1].input))
                                                  ^
TypeError: Cannot read property '1' of undefined
    at Parser.expect (/Users/user/.nvm/v0.10.29/lib/node_modules/yaml2json/node_modules/yaml/lib/yaml.js:179:51)
    at Parser.parseDoc (/Users/user/.nvm/v0.10.29/lib/node_modules/yaml2json/node_modules/yaml/lib/yaml.js:266:8)
    at Parser.parse (/Users/user/.nvm/v0.10.29/lib/node_modules/yaml2json/node_modules/yaml/lib/yaml.js:232:19)
    at Object.exports.eval (/Users/user/.nvm/v0.10.29/lib/node_modules/yaml2json/node_modules/yaml/lib/yaml.js:384:46)
    at handleInput (/Users/ben/.nvm/v0.10.29/lib/node_modules/yaml2json/index.js:31:17)
    at /Users/user/.nvm/v0.10.29/lib/node_modules/yaml2json/index.js:56:9
    at fs.js:271:14
    at Object.oncomplete (fs.js:107:15)
```

**Comment by TreeRex** [comment]
A coworker (a Windows user) found that yaml files using CR/LF line endings cause yaml2json to fail spectacularly. I'm a bit nonplused that line endings actually have any effect on the conversion. Or does YAML require Unix line terminators?
